dynaconf_merge: '@bool True'

development:
  # Development Configuration

  telegrambot:
    token: '@str 6572388011:AAHDa9l65HQAjGgU4-10q3kQNmdkFboCWWQ'
  postgresql:
    scheme: '@str postgresql+asyncpg'
    port: '@int 5432'
    user: '@str ghost'
    password: '@str qwerty'
    path: '@str database'

release:
  # Release configuration
  
  postgresql:
    scheme: '@str postgresql+asyncpg'
    port: '@int 0000'
    user: '@str '
    password: '@str '
    path: '@str '

